version: "3.0"

services:
  grillpb-db:
    image: postgres:11
#    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  grillpb-app:
    build:
      dockerfile: prod.Dockerfile
    image: grillpb-app
#    restart: always
    command: run
    ports:
      - "6996:6996"
    depends_on:
      - grillpb-db
    volumes:
      - "./front:/app/front"
      - "./back:/app/back"
      - "/app/front/node_modules"
